name: Build checker for skills task
on:
  workflow_dispatch:
    inputs:
      ZIP_HASH:
        description: 'Hash of directory tests/'
        required: true
      PIPELINE_HASH:
        description: 'Hash of .github/workflows/pipeline.yml'
        required: true
      SKILLS_AUTH_TOKEN:
        description: 'Skills company token'
        required: true
      CALLBACK_TASK_ID:
        description: 'Skills task id'
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: skills-backend-checker
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: supply config.go with enviromental variables
        run: >
          export ZIP_HASH=${{ github.event.inputs.ZIP_HASH }};
          export PIPELINE_HASH=${{ github.event.inputs.PIPELINE_HASH }};
          export SKILLS_AUTH_TOKEN=${{ github.event.inputs.SKILLS_AUTH_TOKEN }};
          export CALLBACK_TASK_ID=${{ github.event.inputs.CALLBACK_TASK_ID }};
          cp -pf config.go sourceConfig.go && cat sourceConfig.go | envsubst > config.go && rm sourceConfig.go;
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: task-${{ github.event.inputs.CALLBACK_TASK_ID }}
          build-context: .