name: Build checker for frontend metaclass
on:
  workflow_dispatch:
    inputs:
      ORIGINAL_REPOSITORY:
        description: 'HTTPS-ссылка на github-репозиторий с тестами'
        required: true
      CALLBACK_TASK_ID:
        description: 'Номер задания на lms.metaclass.kts.studio'
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: frontend_hw_checker
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: supply config.go with enviromental variables
        run: >
          export ORIGINAL_REPOSITORY=${{ github.event.inputs.ORIGINAL_REPOSITORY }};
          export LMS_COMPANY_TOKEN=${{ secrets.LMS_COMPANY_TOKEN }};
          export CALLBACK_TASK_ID=${{ github.event.inputs.CALLBACK_TASK_ID }};
          cp -pf config.go sourceConfig.go && cat sourceConfig.go | envsubst > config.go && rm sourceConfig.go;
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ktshub/backend-summer-2021

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ktshub/frontend-hw:task-${{ github.event.inputs.CALLBACK_TASK_ID }}
          labels: ${{ steps.meta.outputs.labels }}